INVALID_TARGETS_TEXT = "指令不正确，或不能含有@全体成员"
PERMISSION_DENIED_TEXT = "权限不足"
SKIP_SELF_KICK_TEXT = "不能踢自己"
SKIP_SUPERUSER_KICK_TEXT = "超级用户不能被踢"
SET_CARD_SUCCESS_TEXT = "改名片操作成功"
SET_ADMIN_SUCCESS_TEXT = "设置管理员操作成功"
UNSET_ADMIN_SUCCESS_TEXT = "取消管理员操作成功"
KICK_SUCCESS_TEXT = "踢人操作执行完毕"
KICK_BLACKLIST_SUCCESS_TEXT = "踢人并拉黑操作执行完毕"
TITLE_ALL_TARGET_DENIED_TEXT = "不能含有@全体成员"
TITLE_OTHER_DENIED_TEXT = "只有超级用户可以修改他人头衔，修改自己头衔请直接使用【头衔 xxx】"
TITLE_DELETE_OTHER_DENIED_TEXT = "只有超级用户可以删除他人头衔，删除自己头衔请直接使用【删头衔】"
MUTE_SUCCESS_TEXT = "禁言操作成功"
MUTE_RANDOM_SUCCESS_TEXT = "用户已被禁言随机时长"
UNMUTE_SUCCESS_TEXT = "解禁操作成功"
WHOLE_BAN_SUCCESS_TEXT = "全体操作成功: {action}"
RECALL_USAGE_TEXT = (
    "指令格式：\n"
    "/撤回 @user n\n"
    "回复指定消息时撤回该条消息；使用艾特时撤回被艾特的人在本群 n*19 历史消息内的所有消息。\n"
    "n 不输入则默认 n = 5"
)
RECALL_FETCH_ERROR_TEXT = "获取群历史消息时发生错误"
RECALL_FAIL_TEXT = "撤回失败"
